# SPDX-License-Identifier: GPL-2.0
#
# Build the bench_list_sort kernel module.
#
# Usage:
#   make -C <kernel-source-tree> M=$PWD modules
#
# Example:
#   make -C /tmp/linux-6.12 M=$(pwd) modules

obj-m := bench_list_sort.o
